version: "3"
services:
  ss-server:
    image: shadowsocks/shadowsocks-libev:latest
    environment:
      - PASSWORD=******
      - METHOD=aes-256-cfb
    ports:
      - "0.0.0.0:8000:8388"
      - "0.0.0.0:8000:8388/udp"
    restart: always

  v-ray-server:
    image: v2ray/official:latest
    ports:
      - "0.0.0.0:8001:8388"
      - "0.0.0.0:8001:8388/udp"
    volumes:
      - ./v2ray-server-config.json:/etc/v2ray/config.json
    restart: always
